In [1]:
import numpy as np

Resources_Matrix = np.array([[100, 200], [150, 250], [200, 300]])
Allocation_Factors = np.array([[1.1, 0.9], [1.2, 1.0]])

Result = np.dot(Resources_Matrix, Allocation_Factors)

print("Resulting Matrix:\n", Result)


Resulting Matrix:
 [[350. 290.]
 [465. 385.]
 [580. 480.]]


In [3]:
import numpy as np

Shift_A_Production = np.array([[100, 120, 130, 140, 150, 160, 170],
                               [90, 110, 120, 130, 140, 150, 160],
                               [80, 100, 110, 120, 130, 140, 150]])

Shift_B_Production = np.array([[50, 60, 70, 80, 90, 100, 110],
                               [40, 50, 60, 70, 80, 90, 100],
                               [30, 40, 50, 60, 70, 80, 90]])

Total_Production = Shift_A_Production + Shift_B_Production

print("Total Production Matrix:\n", Total_Production)


Total Production Matrix:
 [[150 180 200 220 240 260 280]
 [130 160 180 200 220 240 260]
 [110 140 160 180 200 220 240]]


In [4]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

forecast_values = np.array([0.5, 1.0, -1.0, 2.0, -2.0])

sigmoid_output = sigmoid(forecast_values)

print("Sigmoid Output:\n", sigmoid_output)


Sigmoid Output:
 [0.62245933 0.73105858 0.26894142 0.88079708 0.11920292]


In [5]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_gradient(x):
    sigmoid_value = sigmoid(x)
    return sigmoid_value * (1 - sigmoid_value)

input_values = np.array([0.5, 1.0, -1.0, 2.0, -2.0])

sigmoid_gradient_output = sigmoid_gradient(input_values)

print("Sigmoid Gradient Output:\n", sigmoid_gradient_output)


Sigmoid Gradient Output:
 [0.23500371 0.19661193 0.19661193 0.10499359 0.10499359]
